url: "https://avrebarra.github.io"
baseurl: "/baba"
title: "Jekyllwind"
google_analytics: G-6ZHVK1RRQ0

plugins:
  - jekyll-postcss

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

postcss:
  cache: false

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - scripts
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  contents:
    output: true
